services:
  parrot-refactoring-ts:
    build: .
    container_name: ipc26-parrot-ts
    command: sh -c "npm install && tail -f /dev/null"
    working_dir: /srv/workshop-ipc26-munich/refactoring/parrot/ts
    volumes:
      - .:/srv/workshop-ipc26-munich/refactoring/parrot/ts:delegated
