services:
  guess-number-tdd-ts:
    build: .
    container_name: ipc26-guess-number-ts
    command: sh -c "npm install && tail -f /dev/null"
    working_dir: /srv/workshop-ipc26-munich/tdd/guess-random-number/ts
    volumes:
      - .:/srv/workshop-ipc26-munich/tdd/guess-random-number/ts:delegated
